package org.project.collab.task.service;
import jakarta.persistence.criteria.Predicate; import java.util.*; import org.project.collab.common.error.*; import org.project.collab.common.web.PageResponse; import org.project.collab.project.domain.Project; import org.project.collab.project.repository.ProjectRepository; import org.project.collab.task.controller.dto.TaskDtos; import org.project.collab.task.domain.*; import org.project.collab.task.repository.TaskRepository; import org.project.collab.user.domain.User; import org.project.collab.user.repository.UserRepository; import org.springframework.dao.OptimisticLockingFailureException; import org.springframework.data.domain.*; import org.springframework.data.jpa.domain.Specification; import org.springframework.stereotype.Service; import org.springframework.transaction.annotation.Transactional;
@Service public class TaskService {private final TaskRepository tasks;private final ProjectRepository projects;private final UserRepository users;private final MembershipPort memberships;private final TaskConflictVersionReader conflicts;public TaskService(TaskRepository t,ProjectRepository p,UserRepository u,MembershipPort m,TaskConflictVersionReader c){tasks=t;projects=p;users=u;memberships=m;conflicts=c;}
 @Transactional public TaskDtos.Detail create(Long actor,Long pid,TaskDtos.Create r){requireMembership(pid,actor);var p=projects.findById(pid).orElseThrow(()->new BusinessException(ErrorCode.PROJECT_NOT_FOUND));User a=assignee(pid,r.assigneeId());var t=tasks.save(new Task(p,r.title(),r.description(),a,r.status()));tasks.flush();return TaskDtos.Detail.from(t);}
 @Transactional(readOnly=true) public TaskDtos.Detail get(Long actor,Long pid,Long tid){requireMembership(pid,actor);return TaskDtos.Detail.from(requireTask(pid,tid));}
 @Transactional(readOnly=true) public PageResponse<TaskDtos.Summary> list(Long actor,Long pid,String keyword,TaskStatus status,Long assigneeId,boolean unassigned,int page,int size,String sort){requireMembership(pid,actor);if(assigneeId!=null&&unassigned)throw new BusinessException(ErrorCode.INVALID_REQUEST);if(page<0||size<1||size>100)throw new BusinessException(ErrorCode.INVALID_REQUEST);Sort s=parseSort(sort).and(Sort.by(Sort.Direction.DESC,"id"));Pageable pageable=PageRequest.of(page,size,s);Specification<Task> spec=(root,q,cb)->{List<Predicate> ps=new ArrayList<>();ps.add(cb.equal(root.get("project").get("id"),pid));if(keyword!=null&&!keyword.isBlank())ps.add(cb.like(cb.lower(root.get("title")),"%"+keyword.toLowerCase(Locale.ROOT)+"%"));if(status!=null)ps.add(cb.equal(root.get("status"),status));if(assigneeId!=null)ps.add(cb.equal(root.get("assignee").get("id"),assigneeId));if(unassigned)ps.add(cb.isNull(root.get("assignee")));return cb.and(ps.toArray(Predicate[]::new));};return PageResponse.from(tasks.findAll(spec,pageable).map(TaskDtos.Summary::from));}
 @Transactional public TaskDtos.Detail update(Long actor,Long pid,Long tid,TaskDtos.Update r){var membership=requireMembership(pid,actor);var t=requireTask(pid,tid);authorize(actor,t,membership);if(!Objects.equals(t.getVersion(),r.getVersion()))throw new BusinessException(ErrorCode.TASK_VERSION_CONFLICT,t.getVersion());if(!r.hasChanges())throw new BusinessException(ErrorCode.INVALID_REQUEST);if(r.has("title")){if(r.getTitle()==null||r.getTitle().isBlank())throw new BusinessException(ErrorCode.INVALID_REQUEST);t.title(r.getTitle());}if(r.has("description"))t.description(r.getDescription());if(r.has("assigneeId"))t.assign(assignee(pid,r.getAssigneeId()));if(r.has("status")){if(r.getStatus()==null)throw new BusinessException(ErrorCode.INVALID_REQUEST);t.status(r.getStatus());}try{tasks.flush();}catch(OptimisticLockingFailureException e){Long current=conflicts.read(tid).orElseThrow(()->new BusinessException(ErrorCode.TASK_NOT_FOUND));throw new BusinessException(ErrorCode.TASK_VERSION_CONFLICT,current);}return TaskDtos.Detail.from(t);}
 @Transactional public void delete(Long actor,Long pid,Long tid){var m=requireMembership(pid,actor);var t=requireTask(pid,tid);authorize(actor,t,m);tasks.delete(t);}
 private MembershipPort.Membership requireMembership(Long p,Long u){return memberships.find(p,u).orElseThrow(()->new BusinessException(ErrorCode.PROJECT_NOT_FOUND));}
 private Task requireTask(Long p,Long t){return tasks.findByIdAndProjectId(t,p).orElseThrow(()->new BusinessException(ErrorCode.TASK_NOT_FOUND));}
 private User assignee(Long p,Long u){if(u==null)return null;if(memberships.find(p,u).isEmpty())throw new BusinessException(ErrorCode.ASSIGNEE_NOT_MEMBER);return users.findById(u).orElseThrow(()->new BusinessException(ErrorCode.ASSIGNEE_NOT_MEMBER));}
 private void authorize(Long actor,Task t,MembershipPort.Membership m){if((t.getAssignee()==null||!t.getAssignee().getId().equals(actor))&&!m.canManageAnyTask())throw new BusinessException(ErrorCode.TASK_FORBIDDEN);}
 private Sort parseSort(String raw){if(raw==null||raw.isBlank())return Sort.by(Sort.Direction.DESC,"createdAt");String[] x=raw.split(",");Set<String> allowed=Set.of("createdAt","updatedAt","title","status","id");if(!allowed.contains(x[0]))throw new BusinessException(ErrorCode.INVALID_REQUEST);Sort.Direction d=x.length>1?Sort.Direction.fromOptionalString(x[1]).orElseThrow(()->new BusinessException(ErrorCode.INVALID_REQUEST)):Sort.Direction.ASC;return Sort.by(d,x[0]);}}
