package org.project.collab.project.service;
import java.util.*; import org.project.collab.common.error.*; import org.project.collab.project.controller.dto.ProjectDtos; import org.project.collab.project.domain.*; import org.project.collab.project.repository.*; import org.project.collab.user.service.UserService; import org.springframework.stereotype.Service; import org.springframework.transaction.annotation.Transactional;
@Service public class ProjectService {private final ProjectRepository projects;private final ProjectMemberRepository members;private final UserService users;public ProjectService(ProjectRepository p,ProjectMemberRepository m,UserService u){projects=p;members=m;users=u;}
 @Transactional public ProjectDtos.Response create(Long uid,ProjectDtos.Create r){var p=projects.save(new Project(r.name(),r.description()));members.save(new ProjectMember(p,users.requireUser(uid),ProjectRole.OWNER));return response(p,ProjectRole.OWNER,1L,null);}
 @Transactional(readOnly=true) public List<ProjectDtos.Response> list(Long uid){return members.findProjectsForUser(uid).stream().map(m->response(m.getProject(),m.getRole(),members.countByProjectId(m.getProject().getId()),null)).toList();}
 @Transactional(readOnly=true) public ProjectDtos.Response get(Long uid,Long pid){var m=requireMember(pid,uid);return response(m.getProject(),m.getRole(),members.countByProjectId(pid),projects.countTasks(pid));}
 @Transactional public ProjectDtos.Response update(Long uid,Long pid,ProjectDtos.Update r){var m=requireMember(pid,uid);ProjectPermission.administer(m);if(r.has("name")&&(r.getName()==null||r.getName().isBlank()))throw new BusinessException(ErrorCode.INVALID_REQUEST);m.getProject().update(r.getName(),r.has("name"),r.getDescription(),r.has("description"));return response(m.getProject(),m.getRole(),members.countByProjectId(pid),projects.countTasks(pid));}
 @Transactional public void delete(Long uid,Long pid){var m=requireMember(pid,uid);ProjectPermission.owner(m);projects.delete(m.getProject());}
 @Transactional(readOnly=true) public ProjectMember requireMember(Long pid,Long uid){return members.findByProjectIdAndUserId(pid,uid).orElseThrow(()->new BusinessException(ErrorCode.PROJECT_NOT_FOUND));}
 private ProjectDtos.Response response(Project p,ProjectRole role,long mc,Long tc){return new ProjectDtos.Response(p.getId(),p.getName(),p.getDescription(),role,mc,tc,p.getCreatedAt(),p.getUpdatedAt());}}
