package org.project.collab.project.service;
import java.util.*; import org.project.collab.common.error.*; import org.project.collab.project.controller.dto.ProjectDtos; import org.project.collab.project.domain.*; import org.project.collab.project.domain.event.ProjectMemberRemoved; import org.project.collab.project.repository.*; import org.project.collab.user.service.UserService; import org.springframework.context.ApplicationEventPublisher; import org.springframework.dao.DataIntegrityViolationException; import org.springframework.stereotype.Service; import org.springframework.transaction.annotation.*;
@Service public class ProjectMemberService {private final ProjectRepository projects;private final ProjectMemberRepository members;private final UserService users;private final ApplicationEventPublisher events;public ProjectMemberService(ProjectRepository p,ProjectMemberRepository m,UserService u,ApplicationEventPublisher e){projects=p;members=m;users=u;events=e;}
 @Transactional(readOnly=true) public Optional<ProjectRole> findRole(Long p,Long u){return members.findByProjectIdAndUserId(p,u).map(ProjectMember::getRole);}
 @Transactional(readOnly=true) public List<ProjectDtos.MemberResponse> list(Long actor,Long pid){requireActor(pid,actor);return members.findAllWithUser(pid).stream().map(ProjectDtos.MemberResponse::from).toList();}
 @Transactional public ProjectDtos.MemberResponse add(Long actor,Long pid,ProjectDtos.MemberCreate r){var a=requireActor(pid,actor);ProjectPermission.administer(a);var role=r.effectiveRole();guardOwnerRole(a,role,null);if(members.existsByProjectIdAndUserId(pid,r.userId()))throw new BusinessException(ErrorCode.MEMBER_DUPLICATED);var target=users.requireUser(r.userId());try{return ProjectDtos.MemberResponse.from(members.save(new ProjectMember(a.getProject(),target,role)));}catch(DataIntegrityViolationException e){throw new BusinessException(ErrorCode.MEMBER_DUPLICATED);}}
 @Transactional public ProjectDtos.MemberResponse changeRole(Long actor,Long pid,Long uid,ProjectRole role){projects.findByIdForUpdate(pid).orElseThrow(()->new BusinessException(ErrorCode.PROJECT_NOT_FOUND));var a=requireActor(pid,actor);ProjectPermission.administer(a);var target=members.findByProjectIdAndUserId(pid,uid).orElseThrow(()->new BusinessException(ErrorCode.MEMBER_NOT_FOUND));guardOwnerRole(a,role,target.getRole());protectLastOwner(pid,target);target.changeRole(role);return ProjectDtos.MemberResponse.from(target);}
 @Transactional public void remove(Long actor,Long pid,Long uid){projects.findByIdForUpdate(pid).orElseThrow(()->new BusinessException(ErrorCode.PROJECT_NOT_FOUND));var a=requireActor(pid,actor);ProjectPermission.administer(a);var target=members.findByProjectIdAndUserId(pid,uid).orElseThrow(()->new BusinessException(ErrorCode.MEMBER_NOT_FOUND));if(target.getRole()==ProjectRole.OWNER&&a.getRole()!=ProjectRole.OWNER)throw new BusinessException(ErrorCode.OWNER_ROLE_FORBIDDEN);protectLastOwner(pid,target);members.delete(target);events.publishEvent(new ProjectMemberRemoved(pid,uid));}
 private ProjectMember requireActor(Long p,Long u){return members.findByProjectIdAndUserId(p,u).orElseThrow(()->new BusinessException(ErrorCode.PROJECT_NOT_FOUND));}
 private void guardOwnerRole(ProjectMember actor,ProjectRole next,ProjectRole old){if(actor.getRole()!=ProjectRole.OWNER&&(next==ProjectRole.OWNER||old==ProjectRole.OWNER))throw new BusinessException(ErrorCode.OWNER_ROLE_FORBIDDEN);}
 private void protectLastOwner(Long pid,ProjectMember t){if(t.getRole()==ProjectRole.OWNER&&members.countByProjectIdAndRole(pid,ProjectRole.OWNER)==1)throw new BusinessException(ErrorCode.LAST_OWNER_REQUIRED);}}
